Fix tests with node 15
kwhitley/apicache pull request #228
Opened 2020-11-12 09:16 UTC by Chocobozzz

Please after the merge, could you create a patch release?

It blocks node upgrade of projects that uses your library: https://github.com/Chocobozzz/PeerTube/issues/2700

Thanks for your work :)

2020-11-23 11:07 UTC, rimiti commented
@kwhitley Is it possible to merge this PR?

2020-12-08 10:43 UTC, kontrollanten commented
@Chocobozzz Maybe we should remove node 6 support since it's breaking this PR? I think that all support for node <9 [should be removed,](https://en.wikipedia.org/wiki/Node.js#Releases) but I guess that's out of scope for this PR :)

2020-12-08 10:56 UTC, rimiti commented
@kontrollanten Agreed with you, node v6 could be serenely removed.

Like some other users (I guess) I'd like to use the latest Node LTS version, is it possible for you @kwhitley to push -up this urgent topic?

2020-12-08 12:24 UTC, kontrollanten requested changes

2020-12-08 12:24 UTC, kontrollanten commented on .travis.yml
> +  - 6
```suggestion
```

2020-12-08 12:24 UTC, kontrollanten commented on package.json
> +    "node": ">=6.2.0 <=15"
```suggestion
    "node": ">=8.0.0 <=15"
```

2020-12-08 17:35 UTC, rimiti commented on .travis.yml
> +  - 14
👍

2020-12-09 05:46 UTC, kontrollanten commented
As far as I understand the failing tests is due to a race condition in `clearing cache cancels expiration callback`, both trace backs are pointing to that tests. But I've to insight in how apicache works to understand what's supposed to be tested; by the name it looks like it's testing that the expiration callback isn't called, but by the code it looks like something else. Someone with more knowledge are welcome to help :)

2020-12-09 09:04 UTC, Chocobozzz commented
I fixed the expiration tests

2020-12-09 16:19 UTC, kwhitley commented
Thanks for the fix @Chocobozzz!  I got to the failing point yesterday and had to shelve it again...

I'm going to release this (sadly) as a major version, as it absolutely breaks backwards compat (by dropping old Node versions).  The only question is whether to even try to maintain restify support within this new scope.  If no one uses it, better to drop support along with the old Node versions to simplify the codebase and make future support less painful.

Thoughts?

2020-12-09 16:28 UTC, kwhitley commented
Getting this error with the branch:
![image](https://user-images.githubusercontent.com/865416/101657143-2bddb980-3a09-11eb-882e-b33db0f5d953.png)

Then under restify as well:
![image](https://user-images.githubusercontent.com/865416/101657181-3730e500-3a09-11eb-9b5b-6b2f4257edb1.png)

![image](https://user-images.githubusercontent.com/865416/101657221-4021b680-3a09-11eb-9467-4380a3c01c71.png)

2020-12-11 11:32 UTC, rotsee commented
> The only question is whether to even try to maintain restify support within this new scope.

FWIW I use this with Restify in production, and would hate to see that support dropped... :/

2020-12-11 12:45 UTC, Chocobozzz commented
@kwhitley I don't have these errors, and neither does travis. What is your nodejs version? 

This PR was just fixing tests and add node 15 support, not removing node 6 support. I think we should just merge the test fixes, support node 15 and keep compat' with restify and node 6. They worked in 1.5.2 so I don't see why they would not work anymore now.

2020-12-11 13:14 UTC, rimiti commented
Agreed with what you said @Chocobozzz.

2021-01-12 08:14 UTC, Chocobozzz commented
What do you think @kwhitley?

2021-02-03 09:10 UTC, rimiti approved these changes
LGTM

2021-02-21 19:15 UTC, vikasg603 commented
Any update for the new release?
I am using Node 14, and I am continuously getting the warning from npm.

2021-02-23 07:39 UTC, merged

2021-02-23 07:51 UTC, kwhitley commented
Merged and going out tonight... thanks so much @Chocobozzz and everyone else for your patience! <3

Sincerest apologies for how ridiculously long this has taken to push through... I've been swamped with a few other libraries and my upcoming Cloudflare Workers work (on top of full time job)!

Cheers all and thanks again!

2021-02-23 08:05 UTC, Chocobozzz commented
No problem thanks for you work and your lib @kwhitley :kissing_cat: